application: sb-library
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:       #static then dynamic

- url: /app
  static_dir: static/app

- url: /img
  static_dir: static/img

- url: /css
  static_dir: static/bootstrap/css

- url: /fonts
  static_dir: static/fonts

- url: /partials
  static_dir: static/partials

- url: /
  static_files: templates/index.html
  upload: templates/index\.html
  secure: always

- url: /_ah/spi/.*
  script: sblibrary.api
  secure: always

- url: /crons/send_reminder
  script: main.app
  login: admin

- url: /google848be8bc1952dbd2.html
  static_files: templates/google848be8bc1952dbd2.html
  upload: templates/google848be8bc1952dbd2\.html

- url: /tasks/gcsupload
  script: main.app
  login: admin


libraries:

- name: endpoints
  version: latest

# pycrypto library used for OAuth2 (req'd for authenticated APIs)
- name: pycrypto
  version: latest


builtins:
- appstats: on